In [3]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Suryansh\Documents\gitsql\Python-for-DE-Advanced\10_Pandas\Dataset\orders.csv')
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [2]:
df['sales'].sum()

np.float64(15039.599999999999)

In [3]:
df['sales'].mean()

np.float64(300.792)

In [4]:
df['sales'].max()

np.float64(3083.4)

In [5]:
df['sales'].median()

np.float64(74.65)

In [6]:
df['sales'].count()

np.int64(50)

In [8]:
df['sales'].min()

np.float64(2.5)

In [9]:
df['sales'].nunique()

50

In [10]:
df['region'].nunique()

4

In [11]:
df['region'].unique()

<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: str

In [12]:
df['category'].unique()

<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

In [13]:
df.groupby('region')['sales'].sum()

region
Central    3824.8
East       3467.7
South      2085.1
West       5662.0
Name: sales, dtype: float64

In [16]:
df.groupby(['region', 'category'])['sales'].sum()

region   category
Central  Furniture           935.4
         Office Supplies    1227.5
         Technology         1661.9
East     Furniture          3279.0
         Office Supplies     121.9
         Technology           66.8
South    Furniture          1951.5
         Office Supplies     133.6
West     Furniture          2799.7
         Office Supplies     739.6
         Technology         2122.7
Name: sales, dtype: float64

In [18]:
df.groupby('region')['sales'].agg(['min', 'max', 'sum'])

          min     max     sum
region
Central   2.5  1097.5  3824.8
East      3.3  3083.4  3467.7
South    15.6   957.6  2085.1
West      7.3  1706.2  5662.0

In [19]:
df.groupby('region').agg({'sales': 'sum', 'profit':'mean'})

          sales      profit
region
Central  3824.8   -1.294118
East     3467.7 -163.800000
South    2085.1  -17.333333
West     5662.0   43.323529

In [20]:
df['category'].value_counts()

category
Office Supplies    28
Furniture          12
Technology         10
Name: count, dtype: int64

In [ ]:
pd.pivot_table(
    df,
    index= 'region', #region is being used here as index
    columns= 'category', #category will be the column names
    values= 'sales', #values are sales that is aggregated into sum
    aggfunc= 'sum',
    fill_value=0 #fill values fills the null value with zero
)

category  Furniture  Office Supplies  Technology
region
Central       935.4           1227.5      1661.9
East         3279.0            121.9        66.8
South        1951.5            133.6         0.0
West         2799.7            739.6      2122.7

In [38]:
df_orders = pd.read_csv(r'C:\Users\Suryansh\Documents\gitsql\Python-for-DE-Advanced\10_Pandas\Dataset\orders.csv')
df_returns = pd.read_csv(r'C:\Users\Suryansh\Documents\gitsql\Python-for-DE-Advanced\10_Pandas\Dataset\returns.csv')

In [30]:
df_orders

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [28]:
df_returns

  return_order_id return_reason
0  CA-2018-105893   bad quality
1  CA-2018-143336    wrong item
2  CA-2018-146703    wrong item
3  CA-2018-167164         other
4  CA-2019-106320   bad quality
5  CA-2019-115742         other
6  CA-2020-101343   bad quality
7  CA-2020-117590    wrong item

In [41]:
df = pd.merge(left= df_orders, right=df_returns, left_on = 'order_id', right_on= 'return_order_id', how='inner')
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_order_id,return_reason
0,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,CA-2018-105893,bad quality
1,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,CA-2018-167164,other
2,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,CA-2018-143336,wrong item
3,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,CA-2018-143336,wrong item
4,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,CA-2018-143336,wrong item
5,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,CA-2019-106320,bad quality
6,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,CA-2020-117590,wrong item
7,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,CA-2020-117590,wrong item
8,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,CA-2020-101343,bad quality
9,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,CA-2018-146703,wrong item
10,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,CA-2019-115742,other

In [40]:
df = pd.merge(left= df_orders, right= df_returns, left_on = 'order_id', right_on= 'return_order_id', how='left')
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_order_id,return_reason
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,NaN,NaN
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,NaN,NaN
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,NaN,NaN
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,NaN,NaN
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,NaN,NaN
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,NaN,NaN
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,NaN,NaN
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,NaN,NaN
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,NaN,NaN
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,NaN,NaN
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,NaN,NaN
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,NaN,NaN
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,NaN,NaN
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,NaN,NaN
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,NaN,NaN
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,NaN,NaN
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,CA-2018-105893,bad quality
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,CA-2018-167164,other
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,CA-2018-143336,wrong item
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,CA-2018-143336,wrong item
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,CA-2018-143336,wrong item
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,NaN,NaN
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7,NaN,NaN
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,NaN,NaN
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,CA-2019-106320,bad quality
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,NaN,NaN
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,NaN,NaN
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,NaN,NaN
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,NaN,NaN
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,NaN,NaN
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,NaN,NaN
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,NaN,NaN
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,NaN,NaN
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,NaN,NaN
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,NaN,NaN
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,CA-2020-117590,wrong item
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,CA-2020-117590,wrong item
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,NaN,NaN
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,NaN,NaN
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,NaN,NaN
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,NaN,NaN
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,NaN,NaN
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,CA-2020-101343,bad quality
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,NaN,NaN
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,NaN,NaN
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,NaN,NaN
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,CA-2018-146703,wrong item
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,NaN,NaN
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,NaN,NaN
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,CA-2019-115742,other

In [ ]:
df.groupby('return_reason')['sales'].sum() #tells how much sales loss the company bore

return_reason
bad quality    1788.4
other            93.7
wrong item     1745.2
Name: sales, dtype: float64

In [4]:
emp1 = {
    'id': ['UG1','UG2','UG3'],
    'name' : ['Sam', 'Naman', 'Mark'],
    'salary': ['100k', '50k', '80k']
}

emp2 = {
    'id': ['UG4','UG5','UG6'],
    'name' : ['Josh', 'Harry', 'Steve'],
    'salary': ['70k', '50k', '60k']
}

df1 = pd.DataFrame(emp1)
df2 = pd.DataFrame(emp2)

In [52]:
df1

    id   name salary
0  UG1    Sam   100k
1  UG2  Naman    50k
2  UG3   Mark    80k

In [53]:
df2

    id   name salary
0  UG4   Josh    70k
1  UG5  Harry    50k
2  UG6  Steve    60k

In [46]:
df = pd.concat([df1, df2])
df.reset_index(drop=True, inplace=True) 
df

    id   name salary
0  UG1    Sam   100k
1  UG2  Naman    50k
2  UG3   Mark    80k
3  UG4   Josh    70k
4  UG5  Harry    50k
5  UG6  Steve    60k

In [52]:
df = pd.concat([df1, df2], ignore_index=True)
df

    id   name salary
0  UG1    Sam   100k
1  UG2  Naman    50k
2  UG3   Mark    80k
3  UG4   Josh    70k
4  UG5  Harry    50k
5  UG6  Steve    60k